language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

install:
  - composer dump-autoload

before_script:
  - phpunit --version

script:
  # check syntax all PHP files, redirect stderr to file and return 0 if file is empty
  - |
    find . -name '*.php' -not -path "./vendor/*" -exec php -l {} > /dev/null \; 2> /tmp/lint.err
    if [ -s /tmp/lint.err ]
    then
      cat /tmp/lint.err
      return 1
    fi
  - phpunit
